
# 1 "t5mc_mc.c" 
# 1 "<built-in>" 
# 1 "<command-line>" 
# 7 "t5mc_mc.c" 
enum before {beforebefore}; 
#line 8 "t5mc_mc.c"
enum after {afterafter}; 
#line 9 "t5mc_mc.c"
enum around {aroundaround}; 
#line 11 "t5mc_mc.c"
enum call {callcall}; 
#line 12 "t5mc_mc.c"
enum execution {executionexecution}; 
#line 13 "t5mc_mc.c"
enum args {argsargs}; 
#line 14 "t5mc_mc.c"
enum result {resultresult}; 
#line 15 "t5mc_mc.c"
enum infile {infileinfile}; 
#line 16 "t5mc_mc.c"
enum infunc {infuncinfunc}; 
#line 18 "t5mc_mc.c"
enum proceed {proceedproceed}; 
