#!/bin/sh

# Clean up _everything_, especially the files generated by
# bootstrap.sh.  Do not run this from outside the source directory: it
# could delete your files!

# Files to preserve:
#./COPYING
#./INSTALL
#./NEWS
#./README
#./ChangeLog
#./AUTHORS
#./bootstrap.sh
#./cleanup.sh
#./Makefile.am
#./configure.in

set -x

make clean
make distclean

rm -f .in
rm -f config.h.in
rm -f config.h

rm -f aclocal.m4
rm -rf autom4te.cache
rm -f stamp-h1

rm -rf config

rm -f libtool

rm -f configure
rm -f config.log config.status

rm -f Makefile
rm -f Makefile.in

SRC_DIRS="src"

for DIR in $SRC_DIRS
do
    rm -f $DIR/Makefile.in
    rm -f $DIR/Makefile
    rm -rf $DIR/.deps
    rm -rf $DIR/.libs
done
